services:
  ingress:
    image: "nginx"
    configs:
    - source: nginx-conf
      target: /etc/nginx/nginx.conf
    ports:
    - "80:80"

  frontend:
    build:
      context: frontend
      dockerfile: prod.Dockerfile
    environment:
    - PORT=8080
    x-develop:
      watch:
      - action: rebuild
        path: .

  backend:
    build: backend
    environment:
    - HTTP_API_PORT=8080
    volumes:
    - tarantool-data:/var/lib/tarantool

volumes:
  tarantool-data:

configs:
  nginx-conf:
    file: nginx.conf
